//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldApp.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldApp.WPF.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ADD {
            get {
                return ResourceManager.GetString("ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cities.
        /// </summary>
        public static string ADD_CITIES {
            get {
                return ResourceManager.GetString("ADD_CITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add City.
        /// </summary>
        public static string ADD_CITY {
            get {
                return ResourceManager.GetString("ADD_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Continent.
        /// </summary>
        public static string ADD_CONTINENT {
            get {
                return ResourceManager.GetString("ADD_CONTINENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Continents.
        /// </summary>
        public static string ADD_CONTINENTS {
            get {
                return ResourceManager.GetString("ADD_CONTINENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Countries.
        /// </summary>
        public static string ADD_COUNTRIES {
            get {
                return ResourceManager.GetString("ADD_COUNTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        public static string ADD_COUNTRY {
            get {
                return ResourceManager.GetString("ADD_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be null.
        /// </summary>
        public static string CANT_BE_NULL {
            get {
                return ResourceManager.GetString("CANT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital City.
        /// </summary>
        public static string CAPITAL_CITY {
            get {
                return ResourceManager.GetString("CAPITAL_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string CITIES {
            get {
                return ResourceManager.GetString("CITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New city added.
        /// </summary>
        public static string CITY_ADDED {
            get {
                return ResourceManager.GetString("CITY_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City already exist.
        /// </summary>
        public static string CITY_EXIST {
            get {
                return ResourceManager.GetString("CITY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid city.
        /// </summary>
        public static string CITY_INVALID {
            get {
                return ResourceManager.GetString("CITY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CITY_NAME {
            get {
                return ResourceManager.GetString("CITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City outside country does not exist.
        /// </summary>
        public static string CITY_NOTEXIST {
            get {
                return ResourceManager.GetString("CITY_NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New continent added.
        /// </summary>
        public static string CONTINENT_ADDED {
            get {
                return ResourceManager.GetString("CONTINENT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent already exist.
        /// </summary>
        public static string CONTINENT_EXIST {
            get {
                return ResourceManager.GetString("CONTINENT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid continent.
        /// </summary>
        public static string CONTINENT_INVALID {
            get {
                return ResourceManager.GetString("CONTINENT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent Name.
        /// </summary>
        public static string CONTINENT_NAME {
            get {
                return ResourceManager.GetString("CONTINENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continents.
        /// </summary>
        public static string CONTINENTS {
            get {
                return ResourceManager.GetString("CONTINENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries    .
        /// </summary>
        public static string COUNTRIES {
            get {
                return ResourceManager.GetString("COUNTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New country added.
        /// </summary>
        public static string COUNTRY_ADDED {
            get {
                return ResourceManager.GetString("COUNTRY_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country already exist.
        /// </summary>
        public static string COUNTRY_EXIST {
            get {
                return ResourceManager.GetString("COUNTRY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid country.
        /// </summary>
        public static string COUNTRY_INVALID {
            get {
                return ResourceManager.GetString("COUNTRY_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string COUNTRY_NAME {
            get {
                return ResourceManager.GetString("COUNTRY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country outside continent does not exist.
        /// </summary>
        public static string COUNTRY_NOTEXIST {
            get {
                return ResourceManager.GetString("COUNTRY_NOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CURRENCY {
            get {
                return ResourceManager.GetString("CURRENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string FEILD_REQUIRED {
            get {
                return ResourceManager.GetString("FEILD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Common Spoken Language.
        /// </summary>
        public static string MOST_SPOKEN_LANGUAGE {
            get {
                return ResourceManager.GetString("MOST_SPOKEN_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population.
        /// </summary>
        public static string POPULATION {
            get {
                return ResourceManager.GetString("POPULATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewmodel is invalid.
        /// </summary>
        public static string VIEWMODEL_INVALID {
            get {
                return ResourceManager.GetString("VIEWMODEL_INVALID", resourceCulture);
            }
        }
    }
}
